//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBW_Lab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fact
    {
        public int time_id { get; set; }
        public int city_id { get; set; }
        public int store_id { get; set; }
        public int customer_id { get; set; }
        public int order_id { get; set; }
        public int item_id { get; set; }
        public Nullable<double> dollar_sold { get; set; }
        public Nullable<double> avg_sales { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public Nullable<int> item_sold_quantity { get; set; }
        public Nullable<int> num_orders { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Headquarter Headquarter { get; set; }
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
        public virtual Store Store { get; set; }
        public virtual Time Time { get; set; }
    }
}
