//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBW_Lab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailOrderCustomer
    {
        public int customer_id { get; set; }
        public string post_address { get; set; }
        public System.DateTime time_order { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
